name: CI

on:
  push:
    branches: [ risc0 ]
  pull_request:
    branches: [ risc0, "risc0-*" ]
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macOS
            arch: ARM64
            triple: aarch64-apple-darwin
          - os: Linux
            arch: X64
            triple: x86_64-unknown-linux-gnu
    runs-on: [ self-hosted, release, "${{ matrix.os }}", "${{ matrix.arch }}" ]
    steps:
      - name: Install Rust
        uses: risc0/actions-rs-toolchain@v1
        with:
            toolchain: stable
      - uses: lukka/get-cmake@v3.27.4

      - name: Check out risc0/rust
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          path: rust
          fetch-depth: 0

      - name: Check out risc0/risc0
        uses: actions/checkout@v4
        with:
          repository: risc0/risc0
          ref: erik/rzup-for-1.85
          path: risc0

      - name: Build and Archive toolchain
        run: |
          GITHUB_ACTIONS=false cargo run --bin rzup -- build rust --path $GITHUB_WORKSPACE/rust
          tree ../ -L 4
          tar \
            --exclude lib/rustlib/src \
            --exclude lib/rustlib/rustc-src \
            -hczvf \
            ./rust-toolchain-${{ matrix.triple }}.tar.gz \
            -C $GITHUB_WORKSPACE/rust/build/${{ matrix.triple }}/stage2/ \
            .
        working-directory: risc0

      - name: "Upload workflow artifact"
        uses: "actions/upload-artifact@v4"
        with:
          name: "rust-toolchain-${{ matrix.triple }}.tar.gz"
          path: "risc0/rust-toolchain-${{ matrix.triple }}.tar.gz"
